spring:
  application:
    name: m-web
  datasource:
    url: jdbc:mysql://localhost:10006/grtblog?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 7005
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
debug: false
